export enum ChangeStatusEvents {
  NEW = 'NEW',

  SET_TZ = 'SET_TZ',
  SET_URL = 'SET_URL',
  SET_RESPONSIBLE = 'SET_RESPONSIBLE',
  SET_DEADLINE = 'SET_DEADLINE',
  SET_POST_DEADLINE = 'SET_POST_DEADLINE',

  CHANGE_TITLE = 'CHANGE_TITLE',
  CHANGE_TZ = 'CHANGE_TZ',
  CHANGE_URL = 'CHANGE_URL',
  CHANGE_RESPONSIBLE = 'CHANGE_RESPONSIBLE',
  CHANGE_DEADLINE = 'CHANGE_DEADLINE',
  CHANGE_POST_DEADLINE = 'CHANGE_POST_DEADLINE',

  DELETE_TZ = 'DELETE_TZ',
  DELETE_URL = 'DELETE_URL',
  DELETE_RESPONSIBLE = 'DELETE_RESPONSIBLE',
  DELETE_DEADLINE = 'DELETE_DEADLINE',
  DELETE_POST_DEADLINE = 'DELETE_POST_DEADLINE',

  ADD_COMMENT = 'ADD_COMMENT',
  DELETE_COMMENT = 'DELETE_COMMENT',
  DELETE_ALL_COMMENTS = 'DELETE_ALL_COMMENTS',
}
